### PR TITLE
Fixed punctuation error on the landing page (footer section)

### LINKED ISSUE #140: Punctuation error on the landing page (footer section)
#### Which task do you want to work on? 
Punctuation error on the landing page (Footer section)

#### Expected behaviour
"completing one minute survey!"

#### Actual behaviour
"completing one minute survey. !"

### What needs to be done?
Remove the full stop and leave only the exclamation mark.

### Who want to work on this issue?
Jolade (Outreachy Applicant)

photo_2022-10-12_15-36-44
Currently working on it @BatoolMM

### PR DESCRIPTION
**Pull request by Jolah1**
### Summary

Fixed full stop and exclamation mark used together at the same point  on the landing page, footer section #140 .
from: survey. !
to: survey!

Fixes #140 

### What should a reviewer concentrate their feedback on?
full stop and exclamation mark used together at the same point  on the landing page, footer section.

### CODE REVIEW

**Comment by BatoolMM** [comment]
Thank you @Jolah1, can you fix the conflict, please?

**Comment by Jolah1** [comment]
> Thank you @Jolah1, can you fix the conflict, please?

yes please, working on it.

**Comment by Jolah1** [comment]
@BatoolMM merge conflict fixed.

**Review by BatoolMM — APPROVED** [review]
Thank you @Jolah1!

**Pull request merged**
