### PR TITLE
Index - #215

### LINKED ISSUE #215: 26/10/22  There is a typo error on the OPEN SCIENCE page
#### Correcting the typo error on the OPEN SOURCE page

]](https://osc-ksa.com/)

### PR DESCRIPTION
**Pull request by GuddyTech**
### Summary

I fixed the typographical errors which were found in the landing page. The issue was created as  #215

Fixes #215

### 
1. All typos were fixed.
2.  Incorrect word placements were arranged properly.

### CODE REVIEW

**Comment by GuddyTech** [comment]
Hello @BatoolMM @alswajiab @sandygudie I am done with this task. Please kindly review and merge. Thanks.

**Review by BatoolMM — APPROVED** [review]

**Comment by BatoolMM** [comment]
Thank you @GuddyTech, it looks good to me!

**Comment by BatoolMM** [comment]
@all-contributors add @GuddyTech for bug

**Comment by GuddyTech** [comment]
@BatoolMM Thanks a lot for this merge

**Pull request merged**
