### PR TITLE
Updating the navigation bar

### PR DESCRIPTION
**Pull request by Mublin**
corrected the navigation bar transition which works with the scroll of window listener and added a little styling to the navbar component. I am one if the interns from outreachy and blog section is coming soon

### CODE REVIEW

**Review by Mublin — COMMENTED** [review]
Added a blog section, check the model if you like it, I will try and add some transitions too

**Review by Mublin — COMMENTED** [review]
Issue #12 and #87 

> I added the Events in the nav bar onclick it takes you to the event subpage I created 

> I added three cards with each event, title, the name of the speaker, date and language in the event subpage 

> I added the click event when clicking on the cards it take you to the Zenodo website where the slides are;

> I also added the same events in both English and Arabic version of the website

**Comment by BatoolMM** [comment]
Thank you @Mublin for your hard work. You are addressing multiple issues in a single PR. Can you make a single PR for correcting the navigation bar transition - and leave the blog section which has already been worked on using a different PR, please?

**Comment by Mublin** [comment]
Thank you i have done the corrections in #210 @BatoolMM thank you

**Pull request closed without merging**
