### PR TITLE
feat: event cards and external links

### PR DESCRIPTION
**Pull request by adetyaz**
Summary: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/issues/186
Tasks 3
We need to add an events subpage where we can link our events in [Zenodo](https://zenodo.org/communities/1231231664/?page=1&size=20).
3.1 Add this to the nav bar
3.2 Add three cards with each event, title, name of the speaker, and language.
3.3 Each card should direct you to a subpage with a description of the event, speaker, language and a link to the slides from Zenodo.

Fixes
Added event cards on the homepage*
Users can see listed events when they click the Event link on the navbar
The Arabic version of the page is updated

Result
events

### CODE REVIEW

**Comment by sandygudie** [comment]
Welldone @adetyaz I think the task 3.3 is to add a subpage for each of the event cards not to link to its youtube equivalences

**Comment by adetyaz** [comment]
@sandygudie what I did was link to the user page, slide on zenodo, I will create those pages,  is there like a design I can follow to achieve this and what assets will I need and how to get them

**Comment by sandygudie** [comment]
No design is available , the subpage is a detailed page of the event card

**Comment by adetyaz** [comment]
Alright @sandygudie I'll get on it

**Comment by adetyaz** [comment]
@sandygudie someone already worked on it and created a pr

**Comment by sandygudie** [comment]
That’s fine , Just go ahead and do yours

**Comment by adetyaz** [comment]
@sandygudie please how can i get the arabic translation for the arabic portion, i'm done with the englist portion and i made a pr to #191

**Pull request closed without merging**
