### PR TITLE
Created a sub-page for Open Educational Resource page

### PR DESCRIPTION
**Pull request by mutmainaho**
-created a new folder for the sub-pages for easy accessibility and readability 
 - I linked the sub-page to open educational resource 
- I added a summary of open educational resources and also added a link to understand the topic better
- I added an iframe to embed my YouTube video

### CODE REVIEW

**Comment by BatoolMM** [comment]
Wonderful work @mutmainaho, a few things to add:

- You should make space between the footer and the video.
- You have to add an illustration with alternative tags
- Add more resources to read about the topic in a new section called "resources"

We want each page to introduce novice learners to the topic in the easiest way possible, so add resources where they can read more about the topic.

Also, explain how would you improve the website further?

**Comment by mutmainaho** [comment]
Hi @BatoolMM Thanks for the feedback, would work on them soon and send in an updated PR

**Comment by alswajiab** [comment]
Hi @mutmainaho, I'm just wondering if there is any update on your PR.

**Comment by alswajiab** [comment]
Thank you Mutmainah for your coding work. I'm closing this PR now but feel free to reopen it later if you have any updates. Let's add @mutmainaho for her contributions. cc @all-contributors

**Comment by alswajiab** [comment]
@all-contributors please add @mutmainaho for code.

**Pull request closed without merging**
