### PR TITLE
fixed bug in arabic page

### PR DESCRIPTION
**Pull request by sandygudie**
Description
A quick fix to the bug in the Arabic page for PR https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/187

Bug: Misaligned Event cards in the Arabic page

### CODE REVIEW

**Comment by sandygudie** [comment]
@BatoolMM  the fix https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/214

**Review by BatoolMM — CHANGES_REQUESTED** [review]
Thank you for the speedy fix, can you move the section (before the UNESCO), please?

**Comment by BatoolMM** [comment]
Let me know when it's ready to be merged!

**Comment by sandygudie** [comment]
@BatoolMM it's ready ti be merged

**Review by BatoolMM — APPROVED** [review]

**Comment by BatoolMM** [comment]
Thank you @sandygudie

**Pull request merged**
