### PR TITLE
added background color in H1 to be more readable. 

### PR DESCRIPTION
**Pull request by ydv-sahitya**
when I visited the h1 heading was not readable. so I added some background color. @BatoolMM  please check this .

### CODE REVIEW

**Comment by ydv-sahitya** [comment]
so here I gave a black transparent look to be more readable. The **join us** button was near to heading. i have some space. I think now It's look much better. @BatoolMM  can you please check this out? what do you think? thanks

**Comment by BatoolMM** [comment]
Thank you @ydv-sahitya for your work with this PR. It looks like a good idea but the colour doesn't seem to be matching with the theme. I'd like only to keep this background in the text at the very beginning where it says "We promote ...". Would that be possible?

**Comment by ydv-sahitya** [comment]
> Thank you @ydv-sahitya for your work with this PR. It looks like a good idea but the colour doesn't seem to be matching with the theme. I'd like only to keep this background in the text at the very beginning where it says "We promote ...". Would that be possible?

yes, it is possible. I will change that. thanks

**Comment by ydv-sahitya** [comment]
hey, @BatoolMM  quick question:   Open Science Community Saudi Arabia, this text is not very readable. would you like to change anything? if you have any ideas, I can work on them. thanks.

**Pull request closed without merging**
