### PR TITLE
Added two sub pages - Open Source and Open License (With Arabic translations)

### PR DESCRIPTION
**Pull request by timokonkwo**
Hi, my mentor @BatoolMM @alswajiab . Here is the workflow for my PR

### MY SUB PAGE WORK FOR OPEN SOURCE
- I created a new folder called sub page where I housed these two files - open-source.html and ar-open-source.html

- I watched the YouTube video carefully and consulted other resources to gain more knowledge and then I crafted a good summary of the subjects and also linking back to the resources for further reading.

- I added the YouTube video to the open source sub page using an `<iframe>` tag so those that prefer watching video can follow along, however the summary is also extensive.

- I made the sub page which I created to comply with web accessibility standards and also semantic.

### HOW I CAN CONTRIBUTE TO OSCSA WEBSITE
I carefully went through all the pages of the OSCSA website and also the code and I found various ways to contribute. They include but not limited to the following:

- I found out that all the pages of the website are not compliant to web accessibility standards. This means that visually impaired people or those with disability will find it very difficult to navigate the website because of the absence of accessibility like the use of `alt` text, etc. **With my knowledge of web accessibility, I can contribute to making all the pages of the website comply with the international accessibility standards**

-  I also found out that the SEO tags are not used and the whole website is not SEO optimized. This will affect the website from ranking on Google's search page. **I will also contribute and help in implementing the SEO tags to help the OSCSA website rank on google just like I did to my personal portfolio website on GitHub.**

- In the tablet view, the close icon of the website's menu doesn't appear where the menu left off. This makes the UI not so user friendly. **I wish to also help in the CSS and make it more responsive.**

- I also noticed the social links in the footer navigation of the website is not implemented yet. I also wish to contribute to this.

- I can also contribute to removing many redundant styling and non-semantic HTML elements I saw in the website's code base to help in making the website load faster and also more SEO friendly.

- If during the internship, we decide to migrate the website to run on a JavaScript framework such as React, I will gladly contribute towards that because it will help minimize creating different HTML pages for each new feature or page we want to add to the website when it runs on components.

- There are other smaller bugs I found too but if It is permitted I can raise issues on that so I and others can contribute to it too.

Thank you my mentors.

### CODE REVIEW

**Comment by timokonkwo** [comment]
Hi Mentors, @BatoolMM @alswajiab 

I just created another sub page (Open license) together with the first sub page I created.

Am I permitted to keep working on other issues or wait will my PR is reviewed?

**Comment by BatoolMM** [comment]
Thank you @timokonkwo for your amazing work. I like your suggestions, especially the accessibility part. 
Here a few comments about the PR:
- Please address one topic in each PR, this PR should address either open licenses or open software. I recommend that you only address open licenses since open software has been addressed in two other PRs.
- We would like the content to be more concise and organised in once column - similar to this PR #38.
- Add where the text is cited from.
- Add where the image is taken from
- Add a few sentences about the video. 
> This video is part of [Open Life Sciences Programe](https://openlifesci.org/) and the subtitles are available in Arabic and English. The OLS program is for people interested in applying open principles in their work and becoming Open Science ambassadors in their communities.
You may also add a reference for the video:
> If you are re-using the video, please cite: Malvika Sharan, Emmy Tsang, Yo Yehudi, Bérénice Batut, Carlos Martinez, Helena Rasche, Hao Ye, Esther Plomp, Andre Maia Chagas, Georgia Aitkenhead, Suzanne lwai, Otis Smith, Emma Anne Harris, Thomas Mboa, Alex Holinski, Zulidyana Rusnalasari, Nelsy Mtsweni, Rowland Mosbergen, Iratxe Puebla, … Anelda van der Walt. (2021, September 19). Mini Talks/Videos about Open Science from OLS-3 Cohort (v.1.1). Zenodo. https://doi.org/10.5281/zenodo.5515763
- The Arabic alignment needs to be fixed. Arabic is a right-to-left language. Make sure the user can switch between both languages on the same page!
- You can use the [Turing Way](https://the-turing-way.netlify.app/) for illustrations and content

Thank you again for your hard work!

**Comment by timokonkwo** [comment]
Hi, Mentor @BatoolMM @alswajiab 

I just effected the changes you requested on the pages. The separate PR for Open License is here #62 

Thank you so much

**Comment by alswajiab** [comment]
Closing this PR.

https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/62#issuecomment-1273670311

**Pull request closed without merging**
