### PR TITLE
Fixed broken/incorrect link on the landing page

### LINKED ISSUE #152: Broken/Incorrect link on the landing page
### Description
Broken or  incorrect link on the landing page (why join our community) section
Link is returning error 404.

#### Expected behaviour
Onclick the "ArabR" it is expected to take us to the community website as the other links in the section did.

#### Actual behaviour
Link is returning error 404 and and the link there is a github repo of the community instead of the website of the community as present in the other links on the same section.

### How to reproduce
- Go to OSCSA website
- On the landing page click on the "ArabR" link (Why join our community section).

- OS:
Windows 10
Screenshot (117)
photo_2022-10-12_21-44-55

### PR DESCRIPTION
**Pull request by Jolah1**
### Summary
Fixed the broken/wrong link on the landing page by replacing the broken ArabR community github repo link with the ArabR community website link.

Fixes #152 

### What should a reviewer concentrate their feedback on?
Fixed broken/incorrect link on the landing page
photo_2022-10-12_21-44-55

### CODE REVIEW

**Comment by BatoolMM** [comment]
Thank you @Jolah1 for catching this!

@all-contributors add @Jolah1 for bug

**Comment by BatoolMM** [comment]
Can you also fix it in the Arabic page, please?

**Review by BatoolMM — APPROVED** [review]

**Comment by Jolah1** [comment]
> Thank you @Jolah1 for catching this!
> 
> @all-contributors add @Jolah1 for bug

It's a pleasure

**Comment by Jolah1** [comment]
> Can you also fix it in the Arabic page, please?

Alright, working on it now......

**Comment by Jolah1** [comment]
> Can you also fix it in the Arabic page, please?

Fixed.......PR awaiting your review

**Comment by BatoolMM** [comment]
Thank you @Jolah1, can you fix the conflict, please?

**Comment by Jolah1** [comment]
> > Can you also fix it in the Arabic page, please?
> 
> Alright, working on it now......

yes I will, on it.......

**Comment by Jolah1** [comment]
@BatoolMM I have resolved the merge conflict, Thank you.

**Review by BatoolMM — APPROVED** [review]
Awesome, thank you @Jolah1

**Pull request merged**
