### PR TITLE
[24/10/2022] : fix social link icon display

### PR DESCRIPTION
**Pull request by sandygudie**
### Summary
Issue: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/issues/204
In an attempt to improve page loading time, the `preload` attribute was added to the bootstrap` link` tag and this broke the social link icon displayed. However, since the bootstrap assets(icons, CSS, etc) are already downloaded into the project, this may not necessarily affect the page loading speed as opposed to using CDN which would be a perfect use for the `preload` attribute.
This PR is a fix to this issue, I reverted the change made to the bootstrap Icons.

### What should a reviewer concentrate their feedback on?
- [ ] Everything looks ok?

### CODE REVIEW

**Comment by sandygudie** [comment]
@BatoolMM  @alswajiab Please review

**Comment by sandygudie** [comment]
@BatoolMM  @alswajiab 
I noticed the hamburger menu icon for the mobile screen is no more visible on the home page, this is also due to the  changes made to the bootstrap icon. 
image

The revert made in this PR would also fix that

**Comment by sandygudie** [comment]
@BatoolMM  the PR to fix the social icon

**Comment by BatoolMM** [comment]
Ohhh, thank you 🙏

**Pull request merged**
